import { Poppins } from "next/font/google";
import "./globals.css";




const poppins = Poppins({
weight: ['400', '600', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning={true} data-theme='light'
      className={` h-full antialiased`}
    >
      <body className={`${poppins.className} min-h-full  flex flex-col `}  >

        <main className="container mx-auto">
          {children}
        </main>



      </body>
    </html>
  );
}
