import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";





const poppins = Poppins({
weight: ['400', '600', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Dragon-News",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html
  lang="en"
  suppressHydrationWarning={true}
  data-theme='light'
  className="h-full antialiased"
>
  <body className={`${poppins.className} min-h-screen flex flex-col bg-[#9793932b]`} suppressHydrationWarning={true}>


    <main className="container mx-auto ">
      {children}
    </main>

    <ToastContainer />
  </body>
</html>
  )}
